import { Observable, Subject } from "rxjs";
import {ref} from "vue";

export class Broadcast {
    broadcast = new Subject();
}

export const devMode: boolean = false;

export const options = ref({
    time: [
        { value: '1', label: '2023' },
        { value: '2', label: '2022' },
        { value: '3', label: '2021' },
        { value: '4', label: '2020' },
        { value: '5', label: '2019' },
        { value: '6', label: '2018' },
        { value: '7', label: '2017' },
        { value: '8', label: '2016' },
        { value: '9', label: '2015' },
        { value: '10', label: '2014' },
        { value: '11', label: '2013' },
        { value: '12', label: '2012' },
        { value: '13', label: '2011' },
        { value: '14', label: '2010' },
        { value: '15', label: '2009' },
    ],
    fireCase: [
        { value: '1', label: '固体' },
        { value: '2', label: '气体' },
        { value: '3', label: '液体' },
        { value: '4', label: '其它' },
    ],
    fireLevel: [
        { value: '1', label: '特大火灾事故' },
        { value: '2', label: '重大火灾事故' },
        { value: '3', label: '较大火灾事故' },
        { value: '4', label: '一般火灾事故' },
    ],
    areaCase: [
        { value: '1', label: '建筑火灾' },
        { value: '2', label: '生产火灾' },
        { value: '3', label: '交通火灾' },
        { value: '4', label: '森林火灾' },
        { value: '5', label: '其它' },
    ],
    area: [
        { value: '1', label: '江苏' },
        { value: '2', label: '安徽' },
        { value: '3', label: '湖南' },
        { value: '4', label: '江西' },
        { value: '5', label: '浙江' },
        { value: '6', label: '福建' },
        { value: '7', label: '山东' },
        { value: '8', label: '湖北' },
        { value: '9', label: '河南' },
        { value: '10', label: '广东' },
        { value: '11', label: '海南' },
        { value: '12', label: '四川' },
        { value: '13', label: '贵州' },
        { value: '14', label: '云南' },
        { value: '15', label: '陕西' },
        { value: '16', label: '甘肃' },
        { value: '17', label: '青海' },
        { value: '18', label: '河北' },
        { value: '19', label: '山西' },
        { value: '20', label: '黑龙江' },
        { value: '21', label: '吉林' },
        { value: '22', label: '辽宁' },
        { value: '23', label: '内蒙古' },
        { value: '24', label: '广西' },
        { value: '25', label: '西藏' },
        { value: '26', label: '宁夏' },
        { value: '27', label: '新疆' },
        { value: '28', label: '北京' },
        { value: '29', label: '天津' },
        { value: '30', label: '上海' },
        { value: '31', label: '重庆' },
        { value: '32', label: '香港' },
        { value: '33', label: '澳门' },
        { value: '34', label: '台湾' },
    ],
})

export const tableOptions = ref({
    time: {
        1 : '2023',
        2 : '2022',
        3 : '2021',
        4 : '2020',
        5 : '2019',
        6 : '2018',
        7 : '2017',
        8 : '2016',
        9 : '2015',
        10 : '2014',
        11 : '2013',
        12 : '2012',
        13 : '2011',
        14 : '2010',
        15 : '2009'
    },
    fireCase: {
        1 : '固体',
        2 : '气体',
        3 : '液体',
        4 : '其它'
    },
    fireLevel: {
        1 : '特大火灾事故',
        2 : '重大火灾事故',
        3 : '较大火灾事故',
        4 : '一般火灾事故'
    },
    areaCase: {
        1 : '建筑火灾',
        2 : '生产火灾',
        3 : '交通火灾',
        4 : '森林火灾',
        5 : '其它'
    },
    area: {
        1 : '江苏',
        2 : '安徽',
        3 : '湖南',
        4 : '江西',
        5 : '浙江',
        6 : '福建',
        7 : '山东',
        8 : '湖北',
        9 : '河南',
        10 : '广东',
        11 : '海南',
        12 : '四川',
        13 : '贵州',
        14 : '云南',
        15 : '陕西',
        16 : '甘肃',
        17 : '青海',
        18 : '河北',
        19 : '山西',
        20 : '黑龙江',
        21 : '吉林',
        22 : '辽宁',
        23 : '内蒙古',
        24 : '广西',
        25 : '西藏',
        26 : '宁夏',
        27 : '新疆',
        28 : '北京',
        29 : '天津',
        30 : '上海',
        31 : '重庆',
        32 : '香港',
        33 : '澳门',
        34 : '台湾'
    }
})
